FROM ghcr.io/darkmatter-ink/aws-image:main
LABEL org.opencontainers.image.description="Useful image for language and cloud development"
LABEL org.opencontainers.image.source=https://github.com/DarkMatter-Ink/dx
LABEL org.opencontainers.image.licenses=Apache

COPY scripts scripts
RUN bash -ex scripts/install-go.bash